AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  Graphql:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: us.imageland.Handler
      Runtime: java8
      CodeUri: build/libs/lambda-dev-all.jar
      MemorySize: 128
      Timeout: 30
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
            RestApiId:
              Ref: Lambda
        Event2:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
            RestApiId:
              Ref: Lambda
        Event3:
          Type: Api
          Properties:
            Path: /graphql
            Method: options
            RestApiId:
              Ref: Lambda
  Lambda:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /graphql:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Graphql.Arn}/invocations
              responses: {}
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Graphql.Arn}/invocations
              responses: {}
            options:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Graphql.Arn}/invocations
              responses: {}
  GraphqlLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Graphql
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Graphql
      Principal: apigateway.amazonaws.com
