// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f1ea1a21-9438-4732-8244-c5bad07086f8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dHF2ikso7",
    "aws_user_pools_web_client_id": "4r0u2ikhg6ej7qiu24023rqibf",
    "aws_content_delivery_bucket": "dev.imageland.us",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3pzfuw8ozmsfr.cloudfront.net"
};


export default awsmobile;
